name: buildProject

on:
  project:
    created:
jobs:
  configuration:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create issue 1
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          filename: .github/seed-issues/issue-1-template.md
      - name: Create issue 2
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          filename: .github/seed-issues/issue-2-template.md
  
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: POC
          column-name: ToDo
          issue-number: 1
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: POC
          column-name: ToDo
          issue-number: 2

# This workflow prunes old workflow runs for an entire repository.

      - name: Remove runs of the project build job
        uses: actions/github-script@v4 # https://github.com/actions/github-script
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const pages = 5;

            let runs_to_delete = [];

            for (let page = 0; page < pages; page += 1) {
              let response = await github.actions.listWorkflowRuns({
                owner: context.repo.owner,
                page: page,
                per_page: 100,
                repo: context.repo.repo,
                workflow_id: 'cards.yaml'
              });

              if (response.data.workflow_runs.length > 0) {
                for (const run of response.data.workflow_runs) {
                    runs_to_delete.push([run.id, run.name]);
                }
              }
            }

            for (const run of runs_to_delete) {
              console.log(`[Deleting] Run id ${run[0]} of '${run[1]}'.`);
              try {
                await github.actions.deleteWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run[0]
                });
              } catch (error) {
                // ignore errors
              }
            }

# Remove project automation files from repo
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove project automation
        run: |
          rm ./.github/workflows/cards.yaml
          rm -rf ./.github/seed-issues
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          message: "github bot package version update"
          signoff: true
