name: buildProject

on:
  project:
    name: POC
    created:
  #workflow_dispatch: {}

jobs:
  configuration:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create issue 1
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          filename: .github/seed-issues/issue-1-template.md
      - name: Create issue 2
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          filename: .github/seed-issues/issue-2-template.md
  
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: POC
          column-name: ToDo
          issue-number: 1
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: POC
          column-name: ToDo
          issue-number: 2
          
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove project automation
        run: |
          rm ./.github/workflows/card.yaml
          rm -rf ./.github/seed-issues
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          message: "github bot package version update"
          signoff: true

  
