name: buildProjectv
on:
  #workflow_dispatch: {}
  push: {}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  makeIssuesArray:
    if: github.repository != 'n8sOrganization/project-automation'  
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.issueArray.outputs.matrix }}
      matrix2: ${{ steps.issueArray.outputs.matrix2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: issueArray 
        id: issueArray 
        run: |
         issueCount=0
         for file in .github/seed-issues/*; do
           issueCount=$((issueCount+1))
           JSON+=$(echo "{\"issue\":\"$file\",\"issueCount\":$issueCount},")
         done
         JSON=${JSON%?}
         echo "::set-output name=matrix::{\"include\":["$JSON"]}"
         
         issueCount=0
         for file in .github/seed-issues/*; do
           issueCount=$((issueCount+1))
           JSON2+=$(echo "{\"issue\":\"$file\",\"issueCount\":$issueCount},")
         done
         JSON2=${JSON2%?}
         echo "::set-output name=matrix2::[$JSON2]"
  createColumns:
    if: github.repository != 'n8sOrganization/project-automation'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: createProject
        uses: matthewferry/create-a-project@v1
        with:
          name: "POC"
          description: POC Project Board
          columns: |
            ToDo
            inProgress
            Complete      
  createIssues:
    runs-on: ubuntu-latest
    needs: [makeIssuesArray, createColumns]
    strategy:
      matrix: ${{ fromJson(needs.makeIssuesArray.outputs.matrix) }}
    steps:
      - name: setVars
        if: matrix.issueCount != 1
        run: |
          issueNum=$(( (${{ matrix.issueCount }}-1) ))
          fileIssueNum=$((issueNum-1))
          issue=$(echo '${{ needs.makeIssuesArray.outputs.matrix2 }}' | jq --argjson fileIssueNum "$fileIssueNum" '.[$fileIssueNum].issue')
          issueStripped="${issue:1:-1}"
          combinedIssue=$(echo "createIssues ($issueStripped, $issueNum)")
          echo "WAIT_FOR=$combinedIssue" >> $GITHUB_ENV
      - name: Run in order
        if: matrix.issueCount != 1
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: ${{ env.WAIT_FOR }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create issue
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: ${{ matrix.issue }}
      - name: Delay to prevent race
        run: |  
         sleep 5
      - name: Create Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: POC
          column-name: ToDo
          issue-number: ${{ matrix.issueCount }}
