name: buildProject
on:
  push: {}
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  configuration:
    if: github.repository != 'n8sOrganization/project-automation'  
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: createProject
        uses: matthewferry/create-a-project@v1
        with:
          name: "POC"
          description: POC Project Board
          columns: |
            ToDo
            inProgress
            Complete
      - name: Create issue 1
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/seed-issues/issue-1-template.md
      - name: Create issue 2
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/seed-issues/issue-2-template.md
  
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: POC
          column-name: ToDo
          issue-number: 2
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: POC
          column-name: ToDo
          issue-number: 1

